#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi
netstat -tulnp | awk 'NR==2 {print "Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name"} NR>2 {print $1, $2, $3, $4, $5, $6, $7}'
