#!/bin/bash

# Vérifie si le script est exécuté avec les privilèges superutilisateur
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Utilise ss pour afficher les sockets en écoute avec PID et nom du programme
ss -tulnpx | awk 'NR==1 {print "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"} NR>1 {print $1, $2, $3, $4, $5, $6, $7, $8}'