#!/usr/bin/env bash
# Ce script affiche toutes les adresses IPv4 actives sur la machine

# Utiliser la commande 'ip' pour afficher les adresses IPv4
# La commande 'ip -4 addr show' affiche les adresses IPv4
# La commande 'grep inet' filtre les lignes contenant les adresses IP
# 'awk' extrait les adresses IP et 'cut' nettoie les caractères supplémentaires

ip -4 addr show | grep inet | awk '{print $2}' | cut -d/ -f1