#!/usr/bin/env bash
# Ce script affiche toutes les adresses IPv4 actives sur la machine

# Utilisation de la commande ip pour lister les adresses IP et filtrer uniquement les IPv4
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'